/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cauldron_3d_enchanted.glb --transform 
Files: cauldron_3d_enchanted.glb [7.09MB] > C:\Users\aysen\Documents\GitHub\whimsical-portfolio\public\models\cauldron_3d_enchanted-transformed.glb [826.54KB] (88%)
Author: MA3D (https://sketchfab.com/SculptMike)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cauldron-3d-enchanted-93427834e9074868840a3471ebe57dd4
Title: Cauldron 3D Enchanted
*/

"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Cauldron(props) {
  const { nodes, materials } = useGLTF(
    "/models/cauldron_3d_enchanted-transformed.glb"
  );

  const modelRef = useRef();

  useFrame((state, delta, xrFrame) => {
    modelRef.current.position.y = -1 + Math.sin(state.clock.elapsedTime) * 0.2;
  });

  return (
    <group
      {...props}
      ref={modelRef}
      dispose={null}
      position={[0, -0.3, -0.5]}
      rotation={[0, -Math.PI / 2, -0.5]}
      scale={[0.8, 0.8, 0.8]}
    >
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.022"]}
        position={[-0.104, 1.737, 0.075]}
        scale={[1.222, 1.382, 1.202]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials["Material.036"]}
        position={[-0.119, 1.823, 0.07]}
        scale={[1.101, 0.151, 1.101]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.034"]}
        position={[-0.104, 1.49, -1.098]}
        rotation={[-0.723, 0, 0]}
        scale={[0.641, 0.06, 0.081]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials["Material.035"]}
        position={[-0.104, 1.49, 1.236]}
        rotation={[-2.419, 0.004, 3.138]}
        scale={[0.641, 0.06, 0.081]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["Material.082"]}
        position={[-1.52, 0.05, 0.688]}
        rotation={[0.136, -0.385, -0.072]}
        scale={[0.931, 0.581, 0.902]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["Material.027"]}
        scale={[1.476, 0.179, 1.476]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials["Material.004"]}
        position={[0.158, 0.072, -1.442]}
        rotation={[-0.19, -0.384, 3.018]}
        scale={[1.045, 0.582, 0.922]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials["Material.028"]}
        position={[0.073, 0.128, 0.504]}
        rotation={[-0.245, 0.41, -3.041]}
        scale={[-0.228, 0.113, 0.891]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials["Material.023"]}
        position={[-0.116, 0.211, -0.569]}
        rotation={[0.392, -0.846, -2.79]}
        scale={[-0.228, 0.113, 0.891]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.material_0}
        position={[-0.143, 1.683, -0.016]}
        scale={[0.376, 0.346, 0.376]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials["Material.037"]}
        position={[-0.162, 1.921, 0.724]}
        scale={[0.22, 0.151, 0.22]}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials["Material.038"]}
        position={[0.474, 1.763, 0.379]}
        rotation={[Math.PI, -1.178, Math.PI]}
        scale={0.22}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials["Material.048"]}
        position={[-0.177, 3.33, 0.803]}
        scale={[0.187, 0.172, 0.187]}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials["Material.046"]}
        position={[0.354, 2.593, -0.465]}
        rotation={[Math.PI, -1.178, Math.PI]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials["Material.050"]}
        position={[0.625, 3.567, 0.058]}
        rotation={[Math.PI, -1.178, Math.PI]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials["Material.051"]}
        position={[-0.188, 3.714, -0.098]}
        scale={[0.059, 0.054, 0.059]}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials["Material.042"]}
        position={[-1.201, 2.614, 0.058]}
        rotation={[Math.PI, -1.178, Math.PI]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_132.geometry}
        material={materials["Material.066"]}
        position={[-0.555, 2.708, 0.465]}
        rotation={[2.667, -0.513, -1.045]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Object_134.geometry}
        material={materials["Material.065"]}
        position={[-1.106, 2.445, -0.022]}
        rotation={[2.667, -0.513, -1.045]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials["Material.064"]}
        position={[-0.028, 2.586, -0.708]}
        rotation={[-1.914, 0.634, -1.208]}
        scale={[0.192, 0.176, 0.192]}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials["Material.063"]}
        position={[0.626, 2.537, 0.638]}
        rotation={[2.667, -0.513, -1.045]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials["Material.061"]}
        position={[0.412, 2.23, -0.115]}
        rotation={[-1.914, 0.634, -1.208]}
        scale={[0.059, 0.054, 0.059]}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials["Material.060"]}
        position={[-0.614, 2.935, -0.959]}
        rotation={[2.667, -0.513, -1.045]}
        scale={0.097}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials["Material.059"]}
        position={[0.116, 2.841, 0.953]}
        rotation={[-1.914, 0.634, -1.208]}
        scale={[0.059, 0.054, 0.059]}
      />
      <mesh
        geometry={nodes.Object_150.geometry}
        material={materials["Material.057"]}
        position={[-0.324, 2.65, -0.548]}
        rotation={[-1.914, 0.634, -1.208]}
        scale={[0.06, 0.055, 0.06]}
      />
      <mesh
        geometry={nodes.Object_154.geometry}
        material={materials["Material.068"]}
        position={[0, -0.199, 0]}
        scale={[2.333, 0.194, 2.333]}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials["Material.049"]}
        position={[0.144, 2.593, 1.065]}
        rotation={[Math.PI, -1.178, Math.PI]}
        scale={0.134}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials["Material.040"]}
        position={[0.084, 2.366, 0.32]}
        scale={[0.241, 0.221, 0.241]}
      />
      <mesh
        geometry={nodes.Object_122.geometry}
        material={materials["Material.045"]}
        position={[0.815, 2.942, -0.098]}
        scale={[0.059, 0.054, 0.059]}
      />
      <mesh
        geometry={nodes.Object_124.geometry}
        material={materials["Material.041"]}
        position={[-0.686, 2.337, -0.277]}
        scale={[0.059, 0.054, 0.059]}
      />
      <mesh
        geometry={nodes.Object_128.geometry}
        material={materials["Material.043"]}
        position={[-0.188, 2.915, 0.647]}
        scale={[0.059, 0.054, 0.059]}
      />
    </group>
  );
}

useGLTF.preload("/models/cauldron_3d_enchanted-transformed.glb");
